language: python
python:
  - '2.6'
  - '2.7'
script:
  - env
  - make clean
  - make DEPTOOL_REPO=`git remote get-url origin` DEPTOOL_REV=`git rev-parse HEAD` all
  - mkdir -p tmp-test && (cd tmp-test && ../dependencies --version)
  - make DEBUG=1 check
  - make install PREFIX=deploy
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: oJP6YaEUq62IuaJGl5ni4UXBYhCLKC5PzH7im7zNZCjnrmz0/BNy7n8ocxxUu3VzBUC2HMkWn/+5gA97EcbBmHSBNrg/AJP82FNsFUVEPIwhirdt5Q9FjiYGmrfMMHJdGscxbCMkyxq8huvsH+d8Q9GMvwlnXfuLsxbhfJ4prNU=
  file: deploy/bin/dependencies
  on:
    repo: guillon/deptools
    tags: true
    python: '2.7'
