#!/bin/sh
#
# This scripts gets a specific version of deptools if not present.
# Then is executes it with the given arguments.
# The actual dependency on the deptools is owned by this script.
# The other dependencies are handled by the deptools DEPENDENCIES files. 
#
set -e
dir=`dirname $0`

# Extract the deptools at the required revision
[ -d deptools -a -z "$FORCE_DEPTOOLS" ] || \
  hg clone http://hg.assembla.com/deptools-dev $dir/deptools-dev && ln -fs deptools-dev $dir/deptools
# Exec deptools
$dir/deptools/deptool.py ${1+"$@"}


