#!/bin/sh
#
# This scripts gets a specific version of deptools if not present.
# Then is executes it with the given arguments.
# The actual dependency on the deptools is owned by this script.
# The other dependencies are handled by the deptools DEPENDENCIES files. 
#
set -e
dir=`dirname $0`

# Extract the deptools at the required revision
if [ ! -e $dir/deptools/deptools/deptool.py ]; then
  git clone -n http://github.com/guillon/deptools.git
  cd deptools
  git checkout --quiet 634ea8b14b705c1f3ac1
  cd ..
fi
# Exec deptools
$dir/deptools/deptools/deptool.py ${1+"$@"}


