#!/usr/bin/env bash
#
# Usage: update-change change_id [ref]
#
# Push a new patchset for the given change_id.
# The new ref is pushed for the code review (default: HEAD).
#
# If the gerrit remote is defined, use it, otherwise
# push directly to the server defined in config.sh.
#
# User email is excluded from the reviewer list.
#

exec `dirname $0`/push-change ${1+"$@"}
